import { Restaurant, Branch, Table, Staff, MenuCategory, MenuItem, Order, WaiterCall } from '@/types/database';

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-001',
    name: 'Muhtasham Restorani',
    slug: 'muhtasham',
    logo_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80',
    banner_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1600&q=80',
    tagline: 'Shohona Dasturxon • Muhtasham Lazzat — Milliy va Yevropa Taomlari',
    currency: 'UZS',
    currency_symbol: "so'm",
    service_fee_percentage: 10,
    phone: '+998 (71) 200-88-88',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rest-002',
    name: 'Savoria Premium Restoran',
    slug: 'savoria',
    logo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=400&q=80',
    banner_url: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1600&q=80',
    tagline: 'Sharqona Mehmondo\'stlik va Zamonaviy Pazandachilik',
    currency: 'UZS',
    currency_symbol: "so'm",
    service_fee_percentage: 12,
    phone: '+998 (71) 205-70-70',
    is_active: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-001',
    restaurant_id: 'rest-001',
    name: 'Muhtasham Markaziy Filial (Toshkent)',
    address: 'Amir Temur shoh ko\'chasi, 88-uy, Toshkent shahri',
    phone: '+998 (71) 200-88-88',
    timezone: 'Asia/Tashkent',
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'branch-002',
    restaurant_id: 'rest-001',
    name: 'Muhtasham Sohil Bo\'yi (Chorvoq)',
    address: 'Bo\'stonliq tumani, Sohil ko\'chasi, 12-uy',
    phone: '+998 (71) 200-88-99',
    timezone: 'Asia/Tashkent',
    is_active: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_TABLES: Table[] = [
  // ==========================================
  // 30 TA STOL — 1-stol ... 30-stol
  // QR tokenlar barqaror va o'qishga qulay: muhtasham-t1 ... muhtasham-t30
  // ==========================================

  // --- Asosiy Zal (1-14 stol) ---
  { id: 'tbl-001', branch_id: 'branch-001', name: '1-stol', number: 1, qr_token: 'muhtasham-t1', capacity: 2, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-002', branch_id: 'branch-001', name: '2-stol', number: 2, qr_token: 'muhtasham-t2', capacity: 2, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-003', branch_id: 'branch-001', name: '3-stol', number: 3, qr_token: 'muhtasham-t3', capacity: 4, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-004', branch_id: 'branch-001', name: '4-stol', number: 4, qr_token: 'muhtasham-t4', capacity: 4, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-005', branch_id: 'branch-001', name: '5-stol', number: 5, qr_token: 'muhtasham-t5', capacity: 4, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-006', branch_id: 'branch-001', name: '6-stol', number: 6, qr_token: 'muhtasham-t6', capacity: 4, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-007', branch_id: 'branch-001', name: '7-stol', number: 7, qr_token: 'muhtasham-t7', capacity: 6, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-008', branch_id: 'branch-001', name: '8-stol', number: 8, qr_token: 'muhtasham-t8', capacity: 6, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-009', branch_id: 'branch-001', name: '9-stol', number: 9, qr_token: 'muhtasham-t9', capacity: 4, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-010', branch_id: 'branch-001', name: '10-stol', number: 10, qr_token: 'muhtasham-t10', capacity: 4, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-011', branch_id: 'branch-001', name: '11-stol', number: 11, qr_token: 'muhtasham-t11', capacity: 2, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-012', branch_id: 'branch-001', name: '12-stol', number: 12, qr_token: 'muhtasham-t12', capacity: 4, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-013', branch_id: 'branch-001', name: '13-stol', number: 13, qr_token: 'muhtasham-t13', capacity: 6, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-014', branch_id: 'branch-001', name: '14-stol', number: 14, qr_token: 'muhtasham-t14', capacity: 6, zone: 'Asosiy Zal', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

  // --- Deraza Yonida (15-20 stol) ---
  { id: 'tbl-015', branch_id: 'branch-001', name: '15-stol', number: 15, qr_token: 'muhtasham-t15', capacity: 2, zone: 'Deraza Yonida', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-016', branch_id: 'branch-001', name: '16-stol', number: 16, qr_token: 'muhtasham-t16', capacity: 2, zone: 'Deraza Yonida', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-017', branch_id: 'branch-001', name: '17-stol', number: 17, qr_token: 'muhtasham-t17', capacity: 4, zone: 'Deraza Yonida', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-018', branch_id: 'branch-001', name: '18-stol', number: 18, qr_token: 'muhtasham-t18', capacity: 4, zone: 'Deraza Yonida', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-019', branch_id: 'branch-001', name: '19-stol', number: 19, qr_token: 'muhtasham-t19', capacity: 4, zone: 'Deraza Yonida', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-020', branch_id: 'branch-001', name: '20-stol', number: 20, qr_token: 'muhtasham-t20', capacity: 6, zone: 'Deraza Yonida', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

  // --- Yozgi Terrasa (21-26 stol) ---
  { id: 'tbl-021', branch_id: 'branch-001', name: '21-stol', number: 21, qr_token: 'muhtasham-t21', capacity: 2, zone: 'Yozgi Terrasa', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-022', branch_id: 'branch-001', name: '22-stol', number: 22, qr_token: 'muhtasham-t22', capacity: 2, zone: 'Yozgi Terrasa', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-023', branch_id: 'branch-001', name: '23-stol', number: 23, qr_token: 'muhtasham-t23', capacity: 2, zone: 'Yozgi Terrasa', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-024', branch_id: 'branch-001', name: '24-stol', number: 24, qr_token: 'muhtasham-t24', capacity: 4, zone: 'Yozgi Terrasa', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-025', branch_id: 'branch-001', name: '25-stol', number: 25, qr_token: 'muhtasham-t25', capacity: 4, zone: 'Yozgi Terrasa', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-026', branch_id: 'branch-001', name: '26-stol', number: 26, qr_token: 'muhtasham-t26', capacity: 4, zone: 'Yozgi Terrasa', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

  // --- VIP Sekciya (27-30 stol) ---
  { id: 'tbl-027', branch_id: 'branch-001', name: '27-stol', number: 27, qr_token: 'muhtasham-t27', capacity: 6, zone: 'VIP Sekciya', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-028', branch_id: 'branch-001', name: '28-stol', number: 28, qr_token: 'muhtasham-t28', capacity: 6, zone: 'VIP Sekciya', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-029', branch_id: 'branch-001', name: '29-stol', number: 29, qr_token: 'muhtasham-t29', capacity: 6, zone: 'VIP Sekciya', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tbl-030', branch_id: 'branch-001', name: '30-stol', number: 30, qr_token: 'muhtasham-t30', capacity: 6, zone: 'VIP Sekciya', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

  // ==========================================
  // 20 TA ALOHIDA XONA — 1-Xona ... 20-Xona
  // QR tokenlar: xona-1 ... xona-20
  // ==========================================
  { id: 'room-001', branch_id: 'branch-001', name: '1-Xona', number: 1, qr_token: 'xona-1', capacity: 6, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-002', branch_id: 'branch-001', name: '2-Xona', number: 2, qr_token: 'xona-2', capacity: 6, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-003', branch_id: 'branch-001', name: '3-Xona', number: 3, qr_token: 'xona-3', capacity: 8, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-004', branch_id: 'branch-001', name: '4-Xona', number: 4, qr_token: 'xona-4', capacity: 8, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-005', branch_id: 'branch-001', name: '5-Xona', number: 5, qr_token: 'xona-5', capacity: 10, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-006', branch_id: 'branch-001', name: '6-Xona', number: 6, qr_token: 'xona-6', capacity: 10, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-007', branch_id: 'branch-001', name: '7-Xona', number: 7, qr_token: 'xona-7', capacity: 12, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-008', branch_id: 'branch-001', name: '8-Xona', number: 8, qr_token: 'xona-8', capacity: 12, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-009', branch_id: 'branch-001', name: '9-Xona', number: 9, qr_token: 'xona-9', capacity: 14, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-010', branch_id: 'branch-001', name: '10-Xona', number: 10, qr_token: 'xona-10', capacity: 15, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-011', branch_id: 'branch-001', name: '11-Xona', number: 11, qr_token: 'xona-11', capacity: 16, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-012', branch_id: 'branch-001', name: '12-Xona', number: 12, qr_token: 'xona-12', capacity: 18, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-013', branch_id: 'branch-001', name: '13-Xona', number: 13, qr_token: 'xona-13', capacity: 20, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-014', branch_id: 'branch-001', name: '14-Xona', number: 14, qr_token: 'xona-14', capacity: 20, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-015', branch_id: 'branch-001', name: '15-Xona', number: 15, qr_token: 'xona-15', capacity: 24, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-016', branch_id: 'branch-001', name: '16-Xona', number: 16, qr_token: 'xona-16', capacity: 25, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-017', branch_id: 'branch-001', name: '17-Xona', number: 17, qr_token: 'xona-17', capacity: 30, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-018', branch_id: 'branch-001', name: '18-Xona', number: 18, qr_token: 'xona-18', capacity: 35, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-019', branch_id: 'branch-001', name: '19-Xona', number: 19, qr_token: 'xona-19', capacity: 40, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'room-020', branch_id: 'branch-001', name: '20-Xona', number: 20, qr_token: 'xona-20', capacity: 50, zone: 'Alohida Xonalar', is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

export const INITIAL_STAFF: Staff[] = [
  {
    id: 'staff-001',
    restaurant_id: 'rest-001',
    branch_id: 'branch-001',
    user_id: 'usr-owner',
    name: 'Sanjar Rahimov',
    email: 'rahimov@muhtasham.uz',
    role: 'RESTAURANT_OWNER',
    phone: '+998 90 111 11 11',
    pin: '1111',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'staff-002',
    restaurant_id: 'rest-001',
    branch_id: 'branch-001',
    user_id: 'usr-chef',
    name: 'Bosh Oshpaz Bobur',
    email: 'oshxona@muhtasham.uz',
    role: 'KITCHEN',
    phone: '+998 93 333 33 33',
    pin: '3333',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'staff-003',
    restaurant_id: 'rest-001',
    branch_id: 'branch-001',
    user_id: 'usr-waiter',
    name: 'Jasur Saidov',
    email: 'ofitsiant@muhtasham.uz',
    role: 'WAITER',
    phone: '+998 91 222 22 22',
    pin: '2222',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'staff-004',
    restaurant_id: 'rest-001',
    branch_id: 'branch-001',
    user_id: 'usr-manager',
    name: 'Madina Karimova',
    email: 'menejer@muhtasham.uz',
    role: 'MANAGER',
    phone: '+998 94 444 44 44',
    pin: '4444',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'staff-005',
    restaurant_id: 'rest-001',
    branch_id: 'branch-001',
    user_id: 'usr-waiter-2',
    name: 'Dilnoza Yo\'ldosheva',
    email: 'ofitsiant2@muhtasham.uz',
    role: 'WAITER',
    phone: '+998 97 555 55 55',
    pin: '5555',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_CATEGORIES: MenuCategory[] = [
  {
    id: 'cat-001',
    restaurant_id: 'rest-001',
    name: 'Oshpaz Tavsiyasi',
    slug: 'oshpaz-tavsiyasi',
    icon: 'Sparkles',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-002',
    restaurant_id: 'rest-001',
    name: 'O\'zbek Milliy Taomlari',
    slug: 'milliy-taomlar',
    icon: 'UtensilsCrossed',
    image_url: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=400&q=80',
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-003',
    restaurant_id: 'rest-001',
    name: 'Shashliklar va Gril',
    slug: 'shashliklar',
    icon: 'Flame',
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=400&q=80',
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-004',
    restaurant_id: 'rest-001',
    name: 'Issiq Taomlar & Steyklar',
    slug: 'issiq-taomlar',
    icon: 'CookingPot',
    image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=400&q=80',
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-005',
    restaurant_id: 'rest-001',
    name: 'Burgerlar & Fast Food',
    slug: 'burgerlar',
    icon: 'Sandwich',
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
    sort_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-006',
    restaurant_id: 'rest-001',
    name: 'Yangi Salatlar',
    slug: 'salatlar',
    icon: 'Salad',
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80',
    sort_order: 6,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-007',
    restaurant_id: 'rest-001',
    name: 'Shirinliklar & Desertlar',
    slug: 'shirinliklar',
    icon: 'Cake',
    image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=400&q=80',
    sort_order: 7,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-008',
    restaurant_id: 'rest-001',
    name: 'Choylar & Salqin Ichimliklar',
    slug: 'ichimliklar',
    icon: 'Wine',
    image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80',
    sort_order: 8,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Oshpaz Tavsiyasi
  {
    id: 'item-001',
    restaurant_id: 'rest-001',
    category_id: 'cat-001',
    name: 'Muhtasham Wagyu Ribay Steyki',
    description: 'Yumshoq Avstraliya Wagyu go\'shti, qora trufel yog\'ida qovurilgan kartoshka pyuresi va maxsus oshpaz sousi bilan tortiladi.',
    price: 180000,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Wagyu go\'shti', 'Trufel yog\'i', 'Kartoshka pyuresi', 'Gril spargasi', 'Dengiz tuzi'],
    dietary_flags: ['halal', 'chef_special', 'gluten_free'],
    spicy_level: 0,
    preparation_time: 25,
    is_available: true,
    is_featured: true,
    option_groups: [
      {
        id: 'opt-meat-temp',
        name: 'Go\'shtning pishish darajasi',
        required: true,
        multiple: false,
        options: [
          { id: 'med-rare', name: 'O\'rtacha pishgan (Medium Rare - Tavsiya)', price: 0 },
          { id: 'medium', name: 'O\'rtacha (Medium)', price: 0 },
          { id: 'well-done', name: 'To\'liq pishgan (Well Done)', price: 0 }
        ]
      },
      {
        id: 'opt-sauce',
        name: 'Qo\'shimcha lazzatlar',
        required: false,
        multiple: true,
        options: [
          { id: 'extra-truffle', name: 'Qo\'shimcha Trufel sousi', price: 20000 },
          { id: 'peppercorn-jus', name: 'Qalampirli qaymoqli sous', price: 15000 }
        ]
      }
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-002',
    restaurant_id: 'rest-001',
    category_id: 'cat-001',
    name: 'Qaymoqli Trufel Tagliatelle Pastasi',
    description: 'Qo\'lda tayyorlangan italyancha pasta, 24 oylik Parmezan pishlog\'i va xushbo\'y qora trufel qaymog\'i bilan.',
    price: 85000,
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Tuxumli tagliatelle', 'Qora trufel', 'Parmezan pishlog\'i', 'Alp qaymog\'i'],
    dietary_flags: ['vegetarian', 'chef_special'],
    spicy_level: 0,
    preparation_time: 18,
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // O'zbek Milliy Taomlari
  {
    id: 'item-004',
    restaurant_id: 'rest-001',
    category_id: 'cat-002',
    name: 'Muhtasham To\'y Oshi (Samarqandcha Plov)',
    description: 'Devzira guruchi, sarxil qo\'y go\'shti, sarg\'ish sabzi, no\'xat, zirk, mayiz, bedana tuxumi va qazi bo\'laklari bilan cho\'yanda damlangan.',
    price: 55000,
    image_url: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Devzira guruch', 'Qo\'y go\'shti', 'Sariq sabzi', 'Qazi', 'Bedana tuxumi', 'No\'xat', 'Zira'],
    dietary_flags: ['halal', 'chef_special'],
    spicy_level: 0,
    preparation_time: 12,
    is_available: true,
    is_featured: true,
    option_groups: [
      {
        id: 'opt-osh-addons',
        name: 'Oshga qo\'shimchalar',
        required: false,
        multiple: true,
        options: [
          { id: 'kazi', name: 'Qo\'shimcha Qazi bo\'lagi (4 dona)', price: 18000 },
          { id: 'quail-eggs', name: 'Qo\'shimcha Bedana tuxumi (3 dona)', price: 8000 },
          { id: 'achichuk-side', name: 'Achichiq pomidor salati', price: 12000 }
        ]
      }
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-005',
    restaurant_id: 'rest-001',
    category_id: 'cat-002',
    name: 'Qozon-Kabob (Yumshoq Qo\'y Go\'shti)',
    description: 'Qozonda qovurilib tilla rang bo\'lgan qo\'y qovurg\'alari, qizargan kartoshkalar va ziravorli piyoz bilan dasturxonga tortiladi.',
    price: 75000,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Qo\'y qovurg\'asi', 'Kartoshka', 'Zira', 'Kashnich', 'Marinadlangan piyoz'],
    dietary_flags: ['halal'],
    spicy_level: 0,
    preparation_time: 20,
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-006',
    restaurant_id: 'rest-001',
    category_id: 'cat-002',
    name: 'Buyuk Ipak Yo\'li Mantisi (5 dona)',
    description: 'Mayin xamir ichida maydalangan qo\'y go\'shti va shirin oshqovoq, qatiq va o\'tkir ajika sousi bilan beriladi.',
    price: 45000,
    image_url: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Maydalangan qo\'y go\'shti', 'Oshqovoq', 'Yupqa xamir', 'Zira', 'Smetana'],
    dietary_flags: ['halal'],
    spicy_level: 0,
    preparation_time: 15,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-007',
    restaurant_id: 'rest-001',
    category_id: 'cat-002',
    name: 'Toshkent Chuchvara Sho\'rvasi',
    description: 'Tiniq go\'shtli bulyonda qo\'lda tugilgan jajji chuchvaralar, yangi kashnich va xushbo\'y rayhon bilan.',
    price: 38000,
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Kichik chuchvaralar', 'Mol go\'shti bulyoni', 'Shivit', 'Kashnich', 'Qaymoq'],
    dietary_flags: ['halal'],
    spicy_level: 0,
    preparation_time: 12,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Shashliklar va Gril
  {
    id: 'item-008',
    restaurant_id: 'rest-001',
    category_id: 'cat-003',
    name: 'Muhtasham Qo\'y Lulya & Qiyma Shashlik',
    description: 'Qayin ko\'mirida pishirilgan sersuv qiyma shashlik, sumaxli qizil piyoz va tandir noni bilan birga beriladi.',
    price: 24000,
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Qo\'y qiymasi', 'Zira', 'Kashnich', 'Sumax', 'Tandir non'],
    dietary_flags: ['halal'],
    spicy_level: 1,
    preparation_time: 18,
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-009',
    restaurant_id: 'rest-001',
    category_id: 'cat-003',
    name: 'Yumshoq Lahm Go\'sht Shashlik (Kuskovoy)',
    description: 'Maxsus ziravorlarda marinadlangan mayin mol go\'shti, ko\'mir cho\'g\'ida pishirilgan.',
    price: 28000,
    image_url: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Lahm mol go\'shti', 'Dumba yog\'i', 'Ziravorlar', 'Piyoz'],
    dietary_flags: ['halal'],
    spicy_level: 0,
    preparation_time: 20,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Burgerlar & Fast Food
  {
    id: 'item-010',
    restaurant_id: 'rest-001',
    category_id: 'cat-005',
    name: 'Klassik Black Angus Burgeri',
    description: '200g sersuv mol go\'shti kotleti, erigan cheddor pishlog\'i, karamellangan piyoz, yangi pomidor va kartoshka fri bilan.',
    price: 52000,
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Angus go\'shti kotleti', 'Cheddor pishlog\'i', 'Karamellangan piyoz', 'Maxsus sous', 'Brioshe bulochkasi'],
    dietary_flags: ['halal'],
    spicy_level: 0,
    preparation_time: 15,
    is_available: true,
    is_featured: true,
    option_groups: [
      {
        id: 'opt-burger-sides',
        name: 'Garnirni tanlang',
        required: true,
        multiple: false,
        options: [
          { id: 'regular-fries', name: 'Qarsildoq Kartoshka Fri (Bazasida)', price: 0 },
          { id: 'cheese-fries', name: 'Pishloqli Kartoshka Fri', price: 10000 },
          { id: 'side-salad', name: 'Yengil yangi salat', price: 6000 }
        ]
      }
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-011',
    restaurant_id: 'rest-001',
    category_id: 'cat-005',
    name: 'Qarsildoq Tovuqli Achchiq Burger',
    description: 'Qarsildoq qovurilgan tovuq filesi, achchiq sous, tuzlangan bodring va karamli salat bilan.',
    price: 46000,
    image_url: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Tovuq filesi', 'Achchiq sous', 'Tuzlangan bodring', 'Karam', 'Maxsus mayonez'],
    dietary_flags: ['halal'],
    spicy_level: 2,
    preparation_time: 15,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Salatlar
  {
    id: 'item-012',
    restaurant_id: 'rest-001',
    category_id: 'cat-006',
    name: 'Burrata va Yangi Pomidor Salati',
    description: 'Yumshoq italyancha Burrata pishlog\'i, suvli pushti pomidorlar, rayhonli pesto sousi va balzamik sirkasi bilan.',
    price: 58000,
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985b?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Burrata pishlog\'i', 'Pushti pomidor', 'Pesto sousi', 'Yong\'oqlar', 'Zaytun yog\'i'],
    dietary_flags: ['vegetarian', 'gluten_free'],
    spicy_level: 0,
    preparation_time: 8,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-013',
    restaurant_id: 'rest-001',
    category_id: 'cat-006',
    name: 'An\'anaviy Achichiq Salati',
    description: 'Yupqa to\'g\'ralgan shirin Yulduz pomidori, oppoq piyoz, binafsharang rayhon va achchiq yashil qalampir.',
    price: 18000,
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Bog\' pomidori', 'Piyoz', 'Rayhon', 'Achchiq qalampir', 'Tuz'],
    dietary_flags: ['vegan', 'vegetarian', 'gluten_free'],
    spicy_level: 1,
    preparation_time: 5,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Shirinliklar
  {
    id: 'item-014',
    restaurant_id: 'rest-001',
    category_id: 'cat-007',
    name: 'Issiq Shokoladli Lava Keyk (Fondant)',
    description: 'Issiq oqib turuvchi qora shokoladli biskvit, qaymoqli vanil muzqaymog\'i va yangi mevalar bilan.',
    price: 36000,
    image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Qora shokolad', 'Vanil muzqaymog\'i', 'Sariyog\'', 'Yalpiz'],
    dietary_flags: ['vegetarian', 'chef_special'],
    spicy_level: 0,
    preparation_time: 12,
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-015',
    restaurant_id: 'rest-001',
    category_id: 'cat-007',
    name: 'Asalli Samarqand Paxlavasi',
    description: '40 qavat yupqa mayin xamir, yong\'oq mag\'zi va tog\' asalidan tayyorlangan qadimiy retseptdagi paxlava.',
    price: 28000,
    image_url: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Yupqa xamir', 'Yong\'oq', 'Tog\' asali', 'Sariyog\''],
    dietary_flags: ['vegetarian', 'halal'],
    spicy_level: 0,
    preparation_time: 5,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Ichimliklar
  {
    id: 'item-016',
    restaurant_id: 'rest-001',
    category_id: 'cat-008',
    name: 'Qorag\'at va Hibiskusli Yangi Limonad',
    description: 'Muzdek gazlangan mineral suv, yangi qorag\'at mevalari, xushbo\'y karkade va laym sharbati bilan.',
    price: 26000,
    image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Qorag\'at', 'Hibiskus damlamasi', 'Laym', 'Yalpiz', 'Muz'],
    dietary_flags: ['vegan', 'gluten_free', 'halal'],
    spicy_level: 0,
    preparation_time: 5,
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item-017',
    restaurant_id: 'rest-001',
    category_id: 'cat-008',
    name: 'Zafaronli Samarqand Ko\'k Choyi (Choynakda)',
    description: 'Eron zafaroni, xushbo\'y hil (kardamon) va Samarqand novvoti bilan damlangan ko\'k choy.',
    price: 18000,
    image_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Ko\'k choy', 'Zafaron', 'Hil', 'Novvot'],
    dietary_flags: ['vegan', 'gluten_free', 'halal'],
    spicy_level: 0,
    preparation_time: 5,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    restaurant_id: 'rest-001',
    branch_id: 'branch-001',
    table_id: 'tbl-012',
    order_number: '#1042',
    status: 'preparing',
    subtotal: 140000,
    service_fee: 14000,
    total: 154000,
    customer_notes: 'Iltimos, go\'shti o\'rtacha pishsin.',
    table_number: 12,
    table_name: '12-stol',
    created_at: new Date(Date.now() - 14 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 60000).toISOString(),
    items: [
      {
        id: 'oi-001',
        order_id: 'ord-1001',
        menu_item_id: 'item-004',
        name_snapshot: 'Muhtasham To\'y Oshi (Samarqandcha Plov)',
        price_snapshot: 55000,
        quantity: 2,
        selected_options: [
          { group_id: 'opt-osh-addons', group_name: 'Oshga qo\'shimchalar', option_id: 'kazi', option_name: 'Qo\'shimcha Qazi bo\'lagi (4 dona)', price: 18000 }
        ],
        total: 110000,
        created_at: new Date(Date.now() - 14 * 60000).toISOString(),
      },
      {
        id: 'oi-002',
        order_id: 'ord-1001',
        menu_item_id: 'item-014',
        name_snapshot: 'Issiq Shokoladli Lava Keyk (Fondant)',
        price_snapshot: 36000,
        quantity: 1,
        total: 36000,
        created_at: new Date(Date.now() - 14 * 60000).toISOString(),
      }
    ]
  },
  {
    id: 'ord-1002',
    restaurant_id: 'rest-001',
    branch_id: 'branch-001',
    table_id: 'tbl-004',
    order_number: '#1043',
    status: 'pending',
    subtotal: 104000,
    service_fee: 10400,
    total: 114400,
    customer_notes: 'Non va choyni birinchi keltiring, iltimos.',
    table_number: 4,
    table_name: '4-stol',
    created_at: new Date(Date.now() - 3 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60000).toISOString(),
    items: [
      {
        id: 'oi-003',
        order_id: 'ord-1002',
        menu_item_id: 'item-010',
        name_snapshot: 'Klassik Black Angus Burgeri',
        price_snapshot: 52000,
        quantity: 2,
        total: 104000,
        created_at: new Date(Date.now() - 3 * 60000).toISOString(),
      }
    ]
  }
];

export const INITIAL_WAITER_CALLS: WaiterCall[] = [
  {
    id: 'wc-001',
    restaurant_id: 'rest-001',
    branch_id: 'branch-001',
    table_id: 'tbl-012',
    table_number: 12,
    table_name: '12-stol (Asosiy Zal)',
    status: 'PENDING',
    call_type: 'SERVICE',
    created_at: new Date(Date.now() - 2 * 60000).toISOString(),
  }
];
